# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.4
    hooks:
      - id: black
        language_version: python3
        args: [--check]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python pylint_multi_packages.py
        language: python
        require_serial: true
